Repository teamterning/Terning-Server, pull requests merged in 2024-08, with the labels that each got.

#95 [♻️ refactor/#94]: 토큰 재발급 로직 리팩토링 및 불필요한 코드 제거
  src/main/java/org/terning/terningserver/controller/AuthController.java
  src/main/java/org/terning/terningserver/controller/swagger/AuthSwagger.java
  src/main/java/org/terning/terningserver/dto/auth/response/AccessTokenGetResponseDto.java
  src/main/java/org/terning/terningserver/dto/auth/response/TokenGetResponseDto.java
  src/main/java/org/terning/terningserver/service/AuthService.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: ♻️ refactor, 🦊장순🦊

#102 [♻️ refactor] 소셜 로그인 > 회원가입 로직 개선
  src/main/java/org/terning/terningserver/controller/AuthController.java
  src/main/java/org/terning/terningserver/controller/swagger/AuthSwagger.java
  src/main/java/org/terning/terningserver/dto/auth/response/AccessTokenGetResponseDto.java
  src/main/java/org/terning/terningserver/dto/auth/response/TokenGetResponseDto.java
  src/main/java/org/terning/terningserver/service/AuthService.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/SignUpService.java
Labels: ♻️ refactor, 🦊장순🦊

#105 [♻️ refactor/#101] SignUpService 클래스 제거 및 AuthService에 회원가입 로직 통합
  src/main/java/org/terning/terningserver/controller/AuthController.java
  src/main/java/org/terning/terningserver/service/AuthService.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/SignUpService.java
Labels: ♻️ refactor, 🦊장순🦊

#109 [🔀 merge] staging > develop 브랜치 병합
  .github/workflows/DOCKER-CD-STAGING.yml
  Dockerfile-staging
  README.md
Labels: 🔀 merge, 💡 test, 🐶정교🐶, 🐰정윤🐰, 🦊장순🦊

#98 [♻️refactor/#97] [2차] 홈화면 > 딱 맞는 대학생 인턴 공고 : 데이터 형식 및 추가 변동사항 적용
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java
  src/main/java/org/terning/terningserver/domain/Scrap.java
  src/main/java/org/terning/terningserver/dto/user/response/HomeAnnouncementsResponseDto.java
  src/main/java/org/terning/terningserver/dto/user/response/HomeResponseDto.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/HomeService.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/main/java/org/terning/terningserver/service/KakaoServiceImpl.java
Labels: ♻️ refactor, 🐶정교🐶

#111 [✨feat] 스테이징 서버 Cors 처리 및 Swagger 설정 추가
  src/main/java/org/terning/terningserver/config/SwaggerConfig.java
  src/main/java/org/terning/terningserver/config/WebMvcConfig.java
Labels: ✨ feat, 🐶정교🐶

#112 [♻️ refactor/#106] 소셜 로그인 > 토큰 생성 메서드 리팩토링 및 파라미터 간소화 작업
  src/main/java/org/terning/terningserver/controller/AuthController.java
  src/main/java/org/terning/terningserver/domain/User.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpWithAuthIdRequestDto.java
  src/main/java/org/terning/terningserver/service/AuthService.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: ♻️ refactor, 🦊장순🦊

#113 [♻️ refactor/#107] 온보딩 > 사용자 필터링 정보 생성 로직 통합 및 개선
  src/main/java/org/terning/terningserver/controller/AuthController.java
  src/main/java/org/terning/terningserver/controller/swagger/AuthSwagger.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/repository/user/UserRepository.java
  src/main/java/org/terning/terningserver/service/AuthService.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/SignUpFilterService.java
Labels: ♻️ refactor, 🦊장순🦊

#118 [🔥!hotfix/#hotDevelop ] 충돌 해결 시도
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: 🔥 !hotfix, 🐶정교🐶, 🦊장순🦊

#115 [🔀 merge] [2차] 코드 리펙토링 사항 적용
  .github/workflows/DEV-CI.yml
  src/main/java/org/terning/terningserver/config/SwaggerConfig.java
  src/main/java/org/terning/terningserver/config/WebMvcConfig.java
  src/main/java/org/terning/terningserver/controller/AuthController.java
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/AuthSwagger.java
  src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java
  src/main/java/org/terning/terningserver/domain/Scrap.java
  src/main/java/org/terning/terningserver/domain/User.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpWithAuthIdRequestDto.java
  src/main/java/org/terning/terningserver/dto/calendar/response/DailyScrapResponseDto.java
  src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyListResponseDto.java
  src/main/java/org/terning/terningserver/dto/user/response/HomeAnnouncementsResponseDto.java
  src/main/java/org/terning/terningserver/dto/user/response/HomeResponseDto.java
  src/main/java/org/terning/terningserver/dto/user/response/UpcomingScrapResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryImpl.java
  src/main/java/org/terning/terningserver/repository/user/UserRepository.java
  src/main/java/org/terning/terningserver/service/AuthService.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/HomeService.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/main/java/org/terning/terningserver/service/KakaoServiceImpl.java
  src/main/java/org/terning/terningserver/service/ScrapService.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
  src/main/java/org/terning/terningserver/service/SignUpFilterService.java
Labels: 🔀 merge
