Repository teamterning/Terning-Server, pull requests merged in 2024-09, with the labels that each got.

#119 [♻️ refactor/#114]: signIn 메서드 리팩토링 및 코드 개선
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: ♻️ refactor, 🦊장순🦊

#122 [♻️ refactor/#120]: 사용하지 않는 TokenGetRequestDto 클래스 삭제
  src/main/java/org/terning/terningserver/dto/auth/request/TokenGetRequestDto.java
Labels: ♻️ refactor, 🦊장순🦊

#124 [✨ feat/#123] 마이페이지 > 프로필 정보 이미지 전달방식 변경 & 마이페이지 > 프로필 수정 기능 추가
  src/main/java/org/terning/terningserver/controller/UserProfileController.java
  src/main/java/org/terning/terningserver/controller/swagger/UserSwagger.java
  src/main/java/org/terning/terningserver/domain/User.java
  src/main/java/org/terning/terningserver/domain/enums/ProfileImage.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpRequestDto.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpWithAuthIdRequestDto.java
  src/main/java/org/terning/terningserver/dto/user/request/Empty.txt
  src/main/java/org/terning/terningserver/dto/user/request/ProfileUpdateRequestDto.java
  src/main/java/org/terning/terningserver/dto/user/response/ProfileResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/UserService.java
  src/main/java/org/terning/terningserver/service/UserServiceImpl.java
Labels: ✨ feat, ♻️ refactor, 🐶정교🐶

#125 [♻️ refactor/#96]: 스크랩 관련 API -> path variable 수정 및 color enum 필드 수정
  src/main/java/org/terning/terningserver/controller/ScrapController.java
  src/main/java/org/terning/terningserver/domain/enums/Color.java
  src/main/java/org/terning/terningserver/dto/scrap/request/CreateScrapRequestDto.java
  src/main/java/org/terning/terningserver/dto/scrap/request/UpdateScrapRequestDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: ♻️ refactor, 🐰정윤🐰

#126 [🔀 merge] [2차] 코드 리펙토링 사항 적용 (2)
  src/main/java/org/terning/terningserver/controller/ScrapController.java
  src/main/java/org/terning/terningserver/controller/UserProfileController.java
  src/main/java/org/terning/terningserver/controller/swagger/UserSwagger.java
  src/main/java/org/terning/terningserver/domain/User.java
  src/main/java/org/terning/terningserver/domain/enums/Color.java
  src/main/java/org/terning/terningserver/domain/enums/ProfileImage.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpRequestDto.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpWithAuthIdRequestDto.java
  src/main/java/org/terning/terningserver/dto/auth/request/TokenGetRequestDto.java
  src/main/java/org/terning/terningserver/dto/scrap/request/CreateScrapRequestDto.java
  src/main/java/org/terning/terningserver/dto/scrap/request/UpdateScrapRequestDto.java
  src/main/java/org/terning/terningserver/dto/user/request/Empty.txt
  src/main/java/org/terning/terningserver/dto/user/request/ProfileUpdateRequestDto.java
  src/main/java/org/terning/terningserver/dto/user/response/ProfileResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
  src/main/java/org/terning/terningserver/service/UserService.java
  src/main/java/org/terning/terningserver/service/UserServiceImpl.java
Labels: 🔀 merge, 🐶정교🐶

#128 [♻️ refactor/#127]: 필터링 관련 API 수정 및 Spring AOP를 사용한 성능테스트 환경 구축
  build.gradle
  src/main/java/org/terning/terningserver/controller/FilterController.java
  src/main/java/org/terning/terningserver/controller/ScrapController.java
  src/main/java/org/terning/terningserver/controller/swagger/FilterSwagger.java
  src/main/java/org/terning/terningserver/controller/swagger/ScrapSwagger.java
  src/main/java/org/terning/terningserver/domain/enums/Color.java
  src/main/java/org/terning/terningserver/domain/enums/Grade.java
  src/main/java/org/terning/terningserver/domain/enums/WorkingPeriod.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpFilterRequestDto.java
  src/main/java/org/terning/terningserver/dto/filter/request/UpdateUserFilterRequestDto.java
  src/main/java/org/terning/terningserver/dto/filter/response/UserFilterDetailResponseDto.java
  src/main/java/org/terning/terningserver/service/FilterService.java
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
  src/main/java/org/terning/terningserver/util/LogAspect.java
  src/main/java/org/terning/terningserver/util/LogExecutionTime.java
Labels: ✨ feat, ♻️ refactor, 🐰정윤🐰

#130 [♻️ refactor/#121]: AuthServiceImpl 리팩토링: 메서드 명명 일관성 및 트랜잭션 관리 개선
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: ♻️ refactor, 🦊장순🦊

#133 [♻️ refactor/#131] 홈화면 > 곧 마감되는 관심 공고 전달 데이터 수정
  src/main/java/org/terning/terningserver/dto/user/response/UpcomingScrapResponseDto.java
Labels: ♻️ refactor, 🐶정교🐶

#135 [🔀 merge] [2차] 코드 리펙토링 사항 적용 (3)
  build.gradle
  src/main/java/org/terning/terningserver/controller/FilterController.java
  src/main/java/org/terning/terningserver/controller/ScrapController.java
  src/main/java/org/terning/terningserver/controller/swagger/FilterSwagger.java
  src/main/java/org/terning/terningserver/controller/swagger/ScrapSwagger.java
  src/main/java/org/terning/terningserver/domain/enums/Color.java
  src/main/java/org/terning/terningserver/domain/enums/Grade.java
  src/main/java/org/terning/terningserver/domain/enums/WorkingPeriod.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpFilterRequestDto.java
  src/main/java/org/terning/terningserver/dto/filter/request/UpdateUserFilterRequestDto.java
  src/main/java/org/terning/terningserver/dto/filter/response/UserFilterDetailResponseDto.java
  src/main/java/org/terning/terningserver/dto/internship_detail/InternshipDetailResponseDto.java
  src/main/java/org/terning/terningserver/dto/search/response/SearchResultResponseDto.java
  src/main/java/org/terning/terningserver/dto/user/response/UpcomingScrapResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/FilterService.java
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
  src/main/java/org/terning/terningserver/service/InternshipDetailService.java
  src/main/java/org/terning/terningserver/service/InternshipDetailServiceImpl.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
  src/main/java/org/terning/terningserver/service/SearchServiceImpl.java
  src/main/java/org/terning/terningserver/util/LogAspect.java
  src/main/java/org/terning/terningserver/util/LogExecutionTime.java
Labels: 🔀 merge, 🐶정교🐶

#136 [♻️ refactor] 소셜로그인 > Swagger와 API 문서 간 정보 불일치 수정
  src/main/java/org/terning/terningserver/controller/AuthController.java
  src/main/java/org/terning/terningserver/controller/swagger/AuthSwagger.java
Labels: ♻️ refactor, 🦊장순🦊

#138 [♻️ refactor] 홈 > 곧 마감되는 관심공고 : 분기 처리를 위한 데이터 형식 추가
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/dto/user/response/UpcomingScrapResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/service/ScrapService.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: ♻️ refactor, 🐶정교🐶

#139 [🔀 merge] [2차] 코드 리펙토링 사항 적용 (4)
  src/main/java/org/terning/terningserver/controller/AuthController.java
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/AuthSwagger.java
  src/main/java/org/terning/terningserver/dto/user/response/UpcomingScrapResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/service/ScrapService.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: 🔀 merge, 🐶정교🐶

#142 [🔨fix] 회원가입 관련 상태 코드 수정 및 예외 처리 변경
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: 🔨 fix, 🦊장순🦊

#146 [🔀 merge] [2차] 코드 리펙토링 사항 적용 (5)
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: 🔀 merge

#148 [🔨 fix/#147] 소셜 로그인 > authId 전처리
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: 🔨 fix, 🦊장순🦊

#149 [🔀 merge] [2차] 코드 리펙토링 사항 적용 (6)
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: 🔀 merge

#150 [♻️ refactor/#143]: 불필요한 중복 에러 메시지 제거 및 코드 정리
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
Labels: ♻️ refactor, 🦊장순🦊

#151 [✨ feat/#144] Discord 회원가입 알림 구현
  src/main/java/org/terning/terningserver/repository/user/UserRepository.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/WebhookService.java
Labels: ✨ feat, 🐶정교🐶

#152 [🔨 fix/#140] 검색화면 totalPages, totalCount 데이터 부정확한 오류 수정
  src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
Labels: 🔨 fix, 🐰정윤🐰

#153 [🔀 merge] [2차] 코드 리펙토링 사항 적용 (7)
  src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/repository/user/UserRepository.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/WebhookService.java
Labels: 🔀 merge, 🐶정교🐶

#157 [✨feat/#156] Discord 회원가입 알림 구현
  src/main/java/org/terning/terningserver/service/WebhookService.java
Labels: ✨ feat

#158 [✨feat/#156] Discord 회원가입 알림 구현
  src/main/java/org/terning/terningserver/service/WebhookService.java
Labels: 🔀 merge, 🐶정교🐶

#159 [🎉 deploy] 터닝 APP 릴리즈를 위한 API 최종 배포 v1.0.0 (2차 스프린트 적용사항 반영)
  src/main/java/org/terning/terningserver/service/WebhookService.java
Labels: 🐶정교🐶, 🎉deploy
