Repository teamterning/Terning-Server, pull requests merged in 2024-12, with the labels that each got.

#174 [♻️ refactor/#173]: updateUserFilter 메서드 리팩토링
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
Labels: ♻️ refactor, 🦊장순🦊

#176 [♻️ refactor/#175]: 공고 데이터 조회 성능 최적화 및 N+1 문제 해결
  build.gradle
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/test/java/org/terning/terningserver/service/legacy/HomeServicePerformanceTest.java
Labels: ♻️ refactor, 💡 test, 🦊장순🦊

#178 [♻️ refactor] N+1 문제 해결 및 HomeServiceImpl 성능 개선
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/test/java/org/terning/terningserver/test_plan.jmt
Labels: ♻️ refactor, 🐶정교🐶

#180 [♻️ refactor/#179] 나에게 딱 맞는 대학생 인턴 공고 API Query Parameter 재조정
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/HomeService.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/test/java/org/terning/terningserver/service/legacy/HomeServicePerformanceTest.java
  test_plan.jmt
Labels: ♻️ refactor, 🐶정교🐶

#182 [🔀 merge] [3차] 코드 리펙토링 사항 적용
  build.gradle
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
  src/main/java/org/terning/terningserver/service/HomeService.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/test/java/org/terning/terningserver/service/legacy/HomeServicePerformanceTest.java
  src/test/java/org/terning/terningserver/test_plan.jmt
  test_plan.jmt
Labels: 🔀 merge, 🐶정교🐶

#183 [✨ feat] 직무필터링, 사용자 필터링 정보, 필터링 재설정(직무, 계획) API 구현
  src/main/java/org/terning/terningserver/domain/Filter.java
  src/main/java/org/terning/terningserver/domain/enums/JobType.java
  src/main/java/org/terning/terningserver/dto/filter/request/UpdateUserFilterRequestDto.java
  src/main/java/org/terning/terningserver/dto/filter/response/UserFilterDetailResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
Labels: ✨ feat, 🐶정교🐶

#184 [🔀 merge] [3차] 코드 리펙토링 사항 적용 (2)
  src/main/java/org/terning/terningserver/domain/Filter.java
  src/main/java/org/terning/terningserver/domain/enums/JobType.java
  src/main/java/org/terning/terningserver/dto/filter/request/UpdateUserFilterRequestDto.java
  src/main/java/org/terning/terningserver/dto/filter/response/UserFilterDetailResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
Labels: 🔀 merge, 🐶정교🐶

#186 [✨feat/#185]: 공고 조회 페이지네이션 기능 도입 및 서비스 로직 개선
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java
  src/main/java/org/terning/terningserver/dto/user/response/HomeAnnouncementsResponseDto.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/HomeService.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
Labels: ✨ feat, 🦊장순🦊

#187 [🔀 merge] [3차] 코드 리펙토링 사항 적용 (3)
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java
  src/main/java/org/terning/terningserver/dto/user/response/HomeAnnouncementsResponseDto.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/HomeService.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
Labels: 🔀 merge, 🦊장순🦊

#189 [🔥 !hotfix] 직무필터링, 사용자 필터링 정보, 필터링 재설정(직무, 계획) API 수정
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
Labels: 🔥 !hotfix, 🐶정교🐶
