Repository teamterning/Terning-Server, pull requests merged in 2024-10, with the labels that each got.

#161 [🔨fix/#160] 인턴 공고 검색 로직 수정
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
Labels: 🔨 fix

#162 [🔀 merge] [2차] 코드 리펙토링 사항 적용 (8)
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
Labels: 🔨 fix, ♻️ refactor, 🐰정윤🐰

#163 [🔀 merge] 스테이징 환경에서는 웹훅을 비활성화하도록 코드 수정
  src/main/java/org/terning/terningserver/service/WebhookService.java
Labels: 🔀 merge, 🐶정교🐶

#164 [🎉 deploy] 터닝 운영서버 배포
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/WebhookService.java
Labels: 🎉deploy

#167 [♻️refactor] DateUtil에서 디데이를 계산할 때, 전체 일자를 고려해 날짜가 계산되도록 수정
  src/main/java/org/terning/terningserver/util/DateUtil.java
Labels: ♻️ refactor, 🐶정교🐶

#168 [🔀 merge] [2차] 코드 리펙토링 사항 적용 (9)
  src/main/java/org/terning/terningserver/util/DateUtil.java
Labels: 🔀 merge, 🐶정교🐶

#169 [🎉 deploy] 터닝 운영서버 배포
  src/main/java/org/terning/terningserver/util/DateUtil.java
Labels: 🐶정교🐶, 🎉deploy
