Repository teamterning/Terning-Server, pull requests merged in 2024-07, with the labels that each got.

#13 [💡test] Discord <> Github 연동 테스트 및 쓸모없는 코드 삭제
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
Labels: ⚰️ del, 💡 test

#15 [✨feat/#14] 도메인 설정 및 연관관계 매핑
  src/main/java/org/terning/terningserver/TerningserverApplication.java
  src/main/java/org/terning/terningserver/domain/Advertisement.java
  src/main/java/org/terning/terningserver/domain/Company.java
  src/main/java/org/terning/terningserver/domain/Filter.java
  src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java
  src/main/java/org/terning/terningserver/domain/Scrap.java
  src/main/java/org/terning/terningserver/domain/User.java
  src/main/java/org/terning/terningserver/domain/common/BaseTimeEntity.java
  src/main/java/org/terning/terningserver/domain/common/Empty.txt
  src/main/java/org/terning/terningserver/domain/enums/AuthType.java
  src/main/java/org/terning/terningserver/domain/enums/Color.java
  src/main/java/org/terning/terningserver/domain/enums/CompanyCategory.java
  src/main/java/org/terning/terningserver/domain/enums/Empty.txt
  src/main/java/org/terning/terningserver/domain/enums/Grade.java
  src/main/java/org/terning/terningserver/domain/enums/State.java
  src/main/java/org/terning/terningserver/domain/enums/WorkingPeriod.java
Labels: ✨ feat, 🐶정교🐶, 🐰정윤🐰

#19 [✨feat/#18] QueryDSL 세팅
  .gitignore
  build.gradle
  src/main/java/org/terning/terningserver/config/QuerydslConfig.java
  src/main/java/org/terning/terningserver/controller/api/Empty.txt
Labels: ✨ feat, 🐶정교🐶

#21 [✅ chore/#20] 성공/에러 메시지 필드 및 enum 수정
  src/main/java/org/terning/terningserver/domain/enums/Grade.java
  src/main/java/org/terning/terningserver/domain/enums/WorkingPeriod.java
  src/main/java/org/terning/terningserver/exception/dto/ErrorResponse.java
  src/main/java/org/terning/terningserver/exception/dto/SuccessResponse.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
Labels: ✅ chore, 🐰정윤🐰

#24 [✅chore/#23] Connection Pool + Hikari CP 세팅
  .gitignore
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: ✅ chore, 🐶정교🐶, 🐰정윤🐰, 🦊장순🦊

#26 [✨ feat/#22] 탐색 > 조회수 많은 공고 API 구현
  src/main/java/org/terning/terningserver/controller/Empty.txt
  src/main/java/org/terning/terningserver/controller/SearchController.java
  src/main/java/org/terning/terningserver/controller/swagger/SearchSwagger.java
  src/main/java/org/terning/terningserver/domain/Company.java
  src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java
  src/main/java/org/terning/terningserver/dto/search/response/PopularAnnouncementListResponse.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/Empty.txt
  src/main/java/org/terning/terningserver/repository/InternshipAnnouncement/InternshipRepository.java
  src/main/java/org/terning/terningserver/repository/InternshipAnnouncement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/InternshipAnnouncement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/Empty.txt
  src/main/java/org/terning/terningserver/service/SearchService.java
Labels: ✨ feat, 🐰정윤🐰

#28 [✨feat/#27] 탐색 > 스크랩 수 많은 공고 API 구현
  src/main/java/org/terning/terningserver/controller/SearchController.java
  src/main/java/org/terning/terningserver/controller/swagger/Empty.txt
  src/main/java/org/terning/terningserver/controller/swagger/SearchSwagger.java
  src/main/java/org/terning/terningserver/domain/Filter.java
  src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java
  src/main/java/org/terning/terningserver/domain/User.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/InternshipAnnouncement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/InternshipAnnouncement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/SearchService.java
  src/main/java/org/terning/terningserver/util/DateUtil.java
Labels: ✨ feat, 🐰정윤🐰

#30 [✨feat/#29] 공고 상세 페이지 API
  src/main/java/org/terning/terningserver/controller/InternshipDetailController.java
  src/main/java/org/terning/terningserver/controller/swagger/InternshipDetailSwagger.java
  src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java
  src/main/java/org/terning/terningserver/domain/Scrap.java
  src/main/java/org/terning/terningserver/domain/enums/CompanyCategory.java
  src/main/java/org/terning/terningserver/dto/internship_detail/InternshipDetailResponse.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepository.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/service/InternshipDetailService.java
  src/main/java/org/terning/terningserver/service/SearchService.java
  src/main/java/org/terning/terningserver/util/DateUtil.java
Labels: ✨ feat, ☁️ db, 🐰정윤🐰

#32 [✨feat/#25] 홈화면 > 딱 맞는 대학생 인턴 공고 API
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java
  src/main/java/org/terning/terningserver/domain/Company.java
  src/main/java/org/terning/terningserver/domain/Filter.java
  src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java
  src/main/java/org/terning/terningserver/domain/Scrap.java
  src/main/java/org/terning/terningserver/domain/User.java
  src/main/java/org/terning/terningserver/domain/enums/Grade.java
  src/main/java/org/terning/terningserver/domain/enums/WorkingPeriod.java
  src/main/java/org/terning/terningserver/dto/user/response/Empty.txt
  src/main/java/org/terning/terningserver/dto/user/response/HomeResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepository.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRespository.java
  src/main/java/org/terning/terningserver/repository/user/UserRepository.java
  src/main/java/org/terning/terningserver/service/HomeService.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/main/java/org/terning/terningserver/service/InternshipDetailService.java
  src/main/java/org/terning/terningserver/util/DateUtil.java
  src/main/resources/application-dev.yml
Labels: ✨ feat, 🐶정교🐶

#34 [✨feat/#33] 홈화면 > 오늘 마감되는 대학생 인턴 공고 API
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java
  src/main/java/org/terning/terningserver/domain/enums/Color.java
  src/main/java/org/terning/terningserver/dto/user/response/TodayScrapResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRespository.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/main/java/org/terning/terningserver/service/ScrapService.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: ✨ feat, 🐶정교🐶

#37 [✨feat/#36] 캘린더 > 월간 캘린더(기본 뷰) 정보 조회 API
  src/main/java/org/terning/terningserver/controller/CalendarController.java
  src/main/java/org/terning/terningserver/controller/swagger/CalendarSwagger.java
  src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyDefaultResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/service/ScrapService.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: ✨ feat, 🐶정교🐶

#41 [✨feat/#40] 캘린더 > 월간 캘린더(리스트 뷰) 정보 조회 API
  src/main/java/org/terning/terningserver/controller/CalendarController.java
  src/main/java/org/terning/terningserver/controller/swagger/CalendarSwagger.java
  src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyListResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/service/ScrapService.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: ✨ feat, 🐶정교🐶

#43 [✨feat/#42] 캘린더 > 일간 캘린더(리스트 뷰) 정보 조회 API
  src/main/java/org/terning/terningserver/controller/CalendarController.java
  src/main/java/org/terning/terningserver/controller/swagger/CalendarSwagger.java
  src/main/java/org/terning/terningserver/dto/calendar/response/DailyScrapResponseDto.java
  src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyDefaultResponseDto.java
  src/main/java/org/terning/terningserver/dto/calendar/response/MonthlyListResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/service/ScrapService.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: ✨ feat, 🐶정교🐶

#45 [✨feat/#44] 마이페이지 > 프로필 정보 조회 API
  src/main/java/org/terning/terningserver/controller/UserProfileController.java
  src/main/java/org/terning/terningserver/controller/swagger/UserSwagger.java
  src/main/java/org/terning/terningserver/dto/user/response/ProfileResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/service/UserService.java
  src/main/java/org/terning/terningserver/service/UserServiceImpl.java
  src/main/resources/application-dev.yml
Labels: ✨ feat, 🐶정교🐶

#46 [✨feat/#39] 스크랩(추가/취소/색상 수정) API
  src/main/java/org/terning/terningserver/controller/InternshipDetailController.java
  src/main/java/org/terning/terningserver/controller/ScrapController.java
  src/main/java/org/terning/terningserver/controller/SearchController.java
  src/main/java/org/terning/terningserver/controller/swagger/InternshipDetailSwagger.java
  src/main/java/org/terning/terningserver/controller/swagger/ScrapSwagger.java
  src/main/java/org/terning/terningserver/controller/swagger/SearchSwagger.java
  src/main/java/org/terning/terningserver/domain/Scrap.java
  src/main/java/org/terning/terningserver/domain/enums/Color.java
  src/main/java/org/terning/terningserver/dto/internship_detail/InternshipDetailResponseDto.java
  src/main/java/org/terning/terningserver/dto/scrap/request/CreateScrapRequestDto.java
  src/main/java/org/terning/terningserver/dto/scrap/request/UpdateScrapRequestDto.java
  src/main/java/org/terning/terningserver/dto/search/response/PopularAnnouncementListResponseDto.java
  src/main/java/org/terning/terningserver/dto/search/response/SearchResultResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/InternshipDetailService.java
  src/main/java/org/terning/terningserver/service/ScrapService.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
  src/main/java/org/terning/terningserver/service/SearchService.java
  src/main/java/org/terning/terningserver/service/SearchServiceImpl.java
Labels: ✨ feat, 🐰정윤🐰

#54 [✨ feat/#47] 사용자 필터링 조회 및 재설정 API
  src/main/java/org/terning/terningserver/controller/FilterController.java
  src/main/java/org/terning/terningserver/controller/swagger/FilterSwagger.java
  src/main/java/org/terning/terningserver/domain/Filter.java
  src/main/java/org/terning/terningserver/dto/filter/request/UserFilterRequestDto.java
  src/main/java/org/terning/terningserver/dto/filter/response/UserFilterResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/service/FilterService.java
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
  src/main/java/org/terning/terningserver/service/InternshipDetailService.java
  src/main/java/org/terning/terningserver/service/InternshipDetailServiceImpl.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: ✨ feat, 🐰정윤🐰

#58 [🔀 merge] 새 브랜치 생성 및 테스트를 위한 Devlop 머지 전 코드 푸시 관련 이슈 4
  .gitignore
  build.gradle
  src/main/generated/org/terning/terningserver/domain/QAdvertisement.java
  src/main/generated/org/terning/terningserver/domain/QCompany.java
  src/main/generated/org/terning/terningserver/domain/QFilter.java
  src/main/generated/org/terning/terningserver/domain/QInternshipAnnouncement.java
  src/main/generated/org/terning/terningserver/domain/QScrap.java
  src/main/generated/org/terning/terningserver/domain/QUser.java
  src/main/generated/org/terning/terningserver/domain/common/QBaseTimeEntity.java
  src/main/java/org/terning/terningserver/config/RestTemplateConfig.java
  src/main/java/org/terning/terningserver/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/config/ValueConfig.java
  src/main/java/org/terning/terningserver/controller/AuthController.java
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/AuthSwagger.java
  src/main/java/org/terning/terningserver/domain/Filter.java
  src/main/java/org/terning/terningserver/domain/Token.java
  src/main/java/org/terning/terningserver/domain/User.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignInRequestDto.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpFilterRequestDto.java
  src/main/java/org/terning/terningserver/dto/auth/request/SignUpRequestDto.java
  src/main/java/org/terning/terningserver/dto/auth/request/TokenGetRequestDto.java
  src/main/java/org/terning/terningserver/dto/auth/response/SignInResponseDto.java
  src/main/java/org/terning/terningserver/dto/auth/response/SignUpFilterResponseDto.java
  src/main/java/org/terning/terningserver/dto/auth/response/TokenGetResponseDto.java
  src/main/java/org/terning/terningserver/exception/dto/ErrorResponse.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/jwt/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/terning/terningserver/jwt/JwtAuthenticationFilter.java
  src/main/java/org/terning/terningserver/jwt/JwtTokenProvider.java
  src/main/java/org/terning/terningserver/jwt/JwtValidationType.java
  src/main/java/org/terning/terningserver/jwt/UserAuthentication.java
  src/main/java/org/terning/terningserver/repository/filter/FilterRepository.java
  src/main/java/org/terning/terningserver/repository/user/UserRepository.java
  src/main/java/org/terning/terningserver/service/AppleService.java
  src/main/java/org/terning/terningserver/service/AppleServiceImpl.java
  src/main/java/org/terning/terningserver/service/AuthService.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/KakaoService.java
  src/main/java/org/terning/terningserver/service/KakaoServiceImpl.java
  src/main/java/org/terning/terningserver/service/SignUpFilterService.java
  src/main/java/org/terning/terningserver/service/SignUpService.java
  src/main/java/org/terning/terningserver/service/UserService.java
  src/main/java/org/terning/terningserver/service/UserServiceImpl.java
  src/main/resources/application-dev.yml
Labels: 🔀 merge, 🦊장순🦊

#62 [🔀fix/#62] application.yml 수정
  .gitignore
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: 🔨 fix, 🐶정교🐶

#64 [🔥!hotfix/#63] CORS 에러 해결
  src/main/java/org/terning/terningserver/config/WebConfig.java
Labels: 🔥 !hotfix

#69 Fix/#68
  src/main/java/org/terning/terningserver/controller/FilterController.java
  src/main/java/org/terning/terningserver/controller/ScrapController.java
  src/main/java/org/terning/terningserver/controller/swagger/ScrapSwagger.java
  src/main/java/org/terning/terningserver/domain/InternshipAnnouncement.java
  src/main/java/org/terning/terningserver/dto/filter/response/UserFilterResponseDto.java
  src/main/java/org/terning/terningserver/jwt/PrincipalHandler.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/FilterService.java
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
  src/main/java/org/terning/terningserver/service/InternshipDetailServiceImpl.java
  src/main/java/org/terning/terningserver/service/ScrapService.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: ✨ feat, 🔨 fix, 🐰정윤🐰

#77 [♻️ refactor] 토큰 재발급 로직 수정
  src/main/java/org/terning/terningserver/dto/auth/response/TokenGetResponseDto.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
Labels: ♻️ refactor, 🦊장순🦊

#83 [🔨fix/#82]: 필터링 재설정 dto 수정
  src/main/java/org/terning/terningserver/domain/enums/Color.java
  src/main/java/org/terning/terningserver/dto/filter/request/UserFilterRequestDto.java
Labels: 🔨 fix, 🐰정윤🐰

#85 [🔥!hotfix/#84] 홈 > 나에게 딱맞는 인턴 공고 조회 응답 데이터 변경
  src/main/java/org/terning/terningserver/dto/user/response/HomeResponseDto.java
Labels: 🔥 !hotfix, 🐶정교🐶

#89 [🔥!hotfix/#88] 탐색 > 검색 결과 화면 응답 데이터 변경
  src/main/java/org/terning/terningserver/dto/search/response/SearchResultResponseDto.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/main/java/org/terning/terningserver/service/SearchServiceImpl.java
Labels: 🔥 !hotfix, 🐶정교🐶

#92 [🔥 !hotfix/#91]: 사용자가 해당 공고를 이미 스크랩했을 경우 예외처리 로직 추가
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
Labels: 🔥 !hotfix, 🐰정윤🐰
