Repository teamterning/Terning-Server, pull requests merged in 2025-06, with the labels that each got.

#250 [🔀 merge] 잘못된 JWT 토큰 요청에 대한 Rate Limit 적용
  build.gradle
  src/main/java/org/terning/terningserver/common/exception/GlobalExceptionHandler.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/JwtTokenVerifier.java
  src/main/java/org/terning/terningserver/common/security/ratelimit/RateLimitingService.java
  src/main/java/org/terning/terningserver/common/util/IpAddressUtil.java
  src/main/java/org/terning/terningserver/internshipAnnouncement/domain/Company.java
  src/main/java/org/terning/terningserver/internshipAnnouncement/domain/InternshipAnnouncement.java
  src/test/java/org/terning/terningserver/common/security/jwt/filter/JwtAuthenticationFilterTest.java
  src/test/java/org/terning/terningserver/service/ScrapServiceTest.java
Labels: 🔀 merge, 🦊장순🦊, size/L

#251 [🔀 merge] 잘못된 JWT 토큰 요청에 대한 Rate Limit 적용
  build.gradle
  src/main/java/org/terning/terningserver/common/exception/GlobalExceptionHandler.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/JwtTokenVerifier.java
  src/main/java/org/terning/terningserver/common/security/ratelimit/RateLimitingService.java
  src/main/java/org/terning/terningserver/common/util/IpAddressUtil.java
  src/main/java/org/terning/terningserver/internshipAnnouncement/domain/Company.java
  src/main/java/org/terning/terningserver/internshipAnnouncement/domain/InternshipAnnouncement.java
  src/test/java/org/terning/terningserver/common/security/jwt/filter/JwtAuthenticationFilterTest.java
  src/test/java/org/terning/terningserver/service/ScrapServiceTest.java
Labels: 🔀 merge, 🦊장순🦊, size/L

#254 [🔀 merge] JWT 필터가 인증 예외 경로를 건너뛰도록 개선
  src/main/java/org/terning/terningserver/common/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/JwtAuthenticationFilter.java
Labels: 🔀 merge, 🦊장순🦊, size/M

#255 [🔀 merge] JWT 필터가 인증 예외 경로를 건너뛰도록 개선
  src/main/java/org/terning/terningserver/common/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/JwtAuthenticationFilter.java
Labels: 🎉deploy, size/M

#257 [Merge] 코드 리펙토링 사항 적용 (Staging -> Main)
  src/main/java/org/terning/terningserver/user/dto/response/ProfileResponseDto.java
Labels: 🔀 merge, 🐶정교🐶, 🎉deploy, size/XS
