Repository teamterning/Terning-Server, pull requests merged in 2025-07, with the labels that each got.

#262 [FEAT] 모니터링 환경 구축 및 과부화 테스트
  build.gradle
  src/main/java/org/terning/terningserver/common/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/external/pushNotification/user/domain/UserSyncEvent.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: ✨ feat, 🦊장순🦊, size/M

#263 [Merge] : 모니터링 환경 구축 및 과부화 테스트
  build.gradle
  src/main/java/org/terning/terningserver/common/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/external/pushNotification/user/domain/UserSyncEvent.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: 🔀 merge, 🦊장순🦊, size/M

#269 [Merge] : 무중단 배포 스크립트 안정성 강화 및 오류 처리 개선
  .github/workflows/DOCKER-CD-STAGING.yml
Labels: 🔀 merge, 🦊장순🦊, size/M

#272 [Merge] 배포 스크립트 내 JSON 환경변수 파싱 오류 수정
  .github/workflows/DOCKER-CD-STAGING.yml
Labels: size/S

#275 [Merge] : JAVA_OPTS 누락으로 인한 컨테이너 실행 실패 및 헬스 체크 오류 해결
  .github/workflows/DOCKER-CD-STAGING.yml
Labels: 🔀 merge, 🦊장순🦊, size/S

#279 Feat : 커스텀 JWT Provider 구현
  src/main/java/org/terning/terningserver/auth/dto/Token.java
  src/main/java/org/terning/terningserver/auth/jwt/JwtProvider.java
  src/main/java/org/terning/terningserver/auth/jwt/exception/JwtErrorCode.java
  src/main/java/org/terning/terningserver/auth/jwt/exception/JwtException.java
  src/main/java/org/terning/terningserver/common/config/ValueConfig.java
  src/main/java/org/terning/terningserver/common/exception/GlobalExceptionHandler.java
  src/main/java/org/terning/terningserver/common/security/jwt/application/JwtClaimsGenerator.java
  src/main/java/org/terning/terningserver/common/security/jwt/application/JwtUserIdExtractor.java
  src/main/java/org/terning/terningserver/common/security/jwt/auth/JwtClaimsParser.java
  src/main/java/org/terning/terningserver/common/security/jwt/auth/UserIdConverter.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/terning/terningserver/external/pushNotification/user/domain/UserSyncEvent.java
Labels: ✨ feat, 🦊장순🦊, size/L

#285 Feat : 스프링 시큐리티 의존성 제거 및 커스텀 인증 전면 적용
  build.gradle
  src/main/java/org/terning/terningserver/auth/config/LoginCheckInterceptor.java
  src/main/java/org/terning/terningserver/auth/dto/request/SignUpWithAuthIdRequestDto.java
  src/main/java/org/terning/terningserver/auth/dto/response/AccessTokenGetResponseDto.java
  src/main/java/org/terning/terningserver/banner/api/BannerSwagger.java
  src/main/java/org/terning/terningserver/calendar/api/CalendarController.java
  src/main/java/org/terning/terningserver/calendar/api/CalendarSwagger.java
  src/main/java/org/terning/terningserver/common/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/common/config/WebConfig.java
  src/main/java/org/terning/terningserver/common/security/jwt/application/JwtClaimsGenerator.java
  src/main/java/org/terning/terningserver/common/security/jwt/application/JwtTokenIssuer.java
  src/main/java/org/terning/terningserver/common/security/jwt/application/JwtTokenManager.java
  src/main/java/org/terning/terningserver/common/security/jwt/application/JwtUserIdExtractor.java
  src/main/java/org/terning/terningserver/common/security/jwt/auth/AuthenticationTokenFactory.java
  src/main/java/org/terning/terningserver/common/security/jwt/auth/CustomUserDetails.java
  src/main/java/org/terning/terningserver/common/security/jwt/auth/JwtClaimsParser.java
  src/main/java/org/terning/terningserver/common/security/jwt/auth/TokenExtractor.java
  src/main/java/org/terning/terningserver/common/security/jwt/auth/UserAuthentication.java
  src/main/java/org/terning/terningserver/common/security/jwt/auth/UserDetailsFactory.java
  src/main/java/org/terning/terningserver/common/security/jwt/auth/UserIdConverter.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/org/terning/terningserver/common/security/jwt/filter/JwtTokenVerifier.java
  src/main/java/org/terning/terningserver/common/security/jwt/provider/JwtKeyProvider.java
  src/main/java/org/terning/terningserver/common/security/jwt/provider/JwtSigner.java
  src/main/java/org/terning/terningserver/external/pushNotification/notification/NotificationUserClient.java
  src/main/java/org/terning/terningserver/filter/api/FilterController.java
  src/main/java/org/terning/terningserver/filter/api/FilterSwagger.java
  src/main/java/org/terning/terningserver/home/api/HomeController.java
  src/main/java/org/terning/terningserver/internshipAnnouncement/api/InternshipDetailController.java
  src/main/java/org/terning/terningserver/internshipAnnouncement/api/InternshipDetailSwagger.java
  src/main/java/org/terning/terningserver/scrap/api/ScrapController.java
  src/main/java/org/terning/terningserver/scrap/api/ScrapSwagger.java
  src/main/java/org/terning/terningserver/search/api/SearchController.java
  src/main/java/org/terning/terningserver/search/api/SearchSwagger.java
  src/main/java/org/terning/terningserver/user/api/UserProfileController.java
  src/main/java/org/terning/terningserver/user/api/UserSwagger.java
  src/test/java/org/terning/terningserver/service/ScrapServiceTest.java
Labels: ✨ feat, 🦊장순🦊, size/XXL

#294 [FEAT] 메인서버의 애플리케이션 성능 측정을 위한 프로메테우스 의존성 추가 (build.gradle)
  build.gradle
  src/main/java/org/terning/terningserver/common/exception/GlobalExceptionHandler.java
Labels: size/S
