Repository teamterning/Terning-Server, pull requests merged in 2025-01, with the labels that each got.

#192 [🔥 !hotfix] 필터링 정보가 모두 null이면 전체 공고가 보이도록 수정
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
Labels: 🔥 !hotfix, 🐶정교🐶

#194 [🔀 merge] [3차] 코드 리펙토링 사항 적용
  build.gradle
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
Labels: ♻️ refactor, 🐶정교🐶

#188 [🔀 merge] [3차] 코드 리펙토링 사항 적용 (3)
  build.gradle
  src/main/java/org/terning/terningserver/controller/HomeController.java
  src/main/java/org/terning/terningserver/controller/swagger/HomeSwagger.java
  src/main/java/org/terning/terningserver/domain/Filter.java
  src/main/java/org/terning/terningserver/domain/enums/JobType.java
  src/main/java/org/terning/terningserver/dto/filter/request/UpdateUserFilterRequestDto.java
  src/main/java/org/terning/terningserver/dto/filter/response/UserFilterDetailResponseDto.java
  src/main/java/org/terning/terningserver/dto/user/response/HomeAnnouncementsResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/AuthServiceImpl.java
  src/main/java/org/terning/terningserver/service/FilterServiceImpl.java
  src/main/java/org/terning/terningserver/service/HomeService.java
  src/main/java/org/terning/terningserver/service/HomeServiceImpl.java
  src/test/java/org/terning/terningserver/service/legacy/HomeServicePerformanceTest.java
  src/test/java/org/terning/terningserver/test_plan.jmt
  test_plan.jmt
Labels: 🔀 merge, 🦊장순🦊

#195 [🔥 !hotfix] [3차] 스테이징 서버 마이그레이션 진행
  .github/workflows/DOCKER-CD-STAGING.yml
  .github/workflows/DOCKER-CD.yml
  README.md
  src/main/java/org/terning/terningserver/config/SwaggerConfig.java
  src/main/java/org/terning/terningserver/config/WebMvcConfig.java
Labels: 🔥 !hotfix, 🐶정교🐶
