Repository teamterning/Terning-Server, pull requests merged in 2025-08, with the labels that each got.

#296 [MERGE] 메인서버의 애플리케이션 성능 측정을 위한 프로메테우스 의존성 추가
  build.gradle
  src/main/java/org/terning/terningserver/common/exception/GlobalExceptionHandler.java
Labels: 🎉deploy, size/S

#298 [♻️ refactor/#297] 신규 유저 로그인 시 응답 데이터 누락 문제 해결
  src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java
Labels: ♻️ refactor, size/XS

#299 [🔀 merge] 신규 유저 로그인 시 응답 데이터 누락 문제 해결
  src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java
Labels: 🔀 merge, 🦊장순🦊, size/XS

#300 [🔀 merge] 신규 유저 로그인 시 응답 데이터 누락 문제 해결
  src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java
Labels: 🔀 merge, 🦊장순🦊, size/XS

#302 fix(auth): 회원가입 시 authId의 Bearer 접두사 처리
  src/main/java/org/terning/terningserver/auth/application/AuthService.java
Labels: ♻️ refactor, size/S

#303 merge : 회원가입 시 authId의 Bearer 접두사 처리
  src/main/java/org/terning/terningserver/auth/application/AuthService.java
Labels: 🔀 merge, 🦊장순🦊, size/S
