Repository teamterning/Terning-Server, pull requests merged in 2025-04, with the labels that each got.

#214 [✨ feat] HTTP 요청/응답 로깅 구현
  src/main/java/org/terning/terningserver/exception/GlobalExceptionHandler.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/logging/CachedHttpServletRequest.java
  src/main/java/org/terning/terningserver/logging/LoggingFilter.java
  src/main/resources/logback-dev.xml
  src/main/resources/logback-local.xml
  src/main/resources/logback-prod.xml
Labels: ✨ feat, size/L

#217 [🔀 merge] [5차] HTTP 요청/응답 로깅 스테이징 서버 반영
  src/main/java/org/terning/terningserver/exception/GlobalExceptionHandler.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/logging/CachedHttpServletRequest.java
  src/main/java/org/terning/terningserver/logging/LoggingFilter.java
  src/main/resources/logback-dev.xml
  src/main/resources/logback-local.xml
  src/main/resources/logback-prod.xml
Labels: size/L

#211 [✨ feat] 소셜 로그인 시 FCM 토큰 검증 및 재발급 여부 응답 처리 로직 구현
  build.gradle
  src/main/java/org/terning/terningserver/auth/application/signin/AuthSignInServiceImpl.java
  src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/external/config/WebClientConfig.java
  src/main/java/org/terning/terningserver/external/dto/FcmTokenReissueRequiredResponse.java
  src/main/java/org/terning/terningserver/external/notification/FcmTokenValidationClient.java
Labels: ✨ feat, 🦊장순🦊, size/L

#215 [✨ feat] 스크랩한 유저를 조회하는 API 구현
  src/main/java/org/terning/terningserver/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/domain/Scrap.java
  src/main/java/org/terning/terningserver/domain/vo/SyncStatus.java
  src/main/java/org/terning/terningserver/external/scrap/api/ScrapExternalApiController.java
  src/main/java/org/terning/terningserver/external/scrap/application/ScrapExternalService.java
  src/main/java/org/terning/terningserver/external/scrap/application/UnsyncedScrapUserReader.java
  src/main/java/org/terning/terningserver/external/scrap/application/UnsyncedScrapUserReaderImpl.java
  src/main/java/org/terning/terningserver/external/scrap/dto/response/UnsyncedScrapUserResponse.java
  src/main/java/org/terning/terningserver/external/scrap/dto/response/UnsyncedScrapUsersResponse.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryImpl.java
Labels: ✨ feat, 🦊장순🦊, size/L

#219 [✨ feat] 동기화 대상 유저 ID 수신 및 상태 반영 API 구현
  src/main/java/org/terning/terningserver/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/external/config/WebClientConfig.java
  src/main/java/org/terning/terningserver/external/scrap/ScrapSyncMarkerImpl.java
  src/main/java/org/terning/terningserver/external/scrap/api/ScrapExternalApiController.java
  src/main/java/org/terning/terningserver/external/scrap/application/ScrapExternalService.java
  src/main/java/org/terning/terningserver/external/scrap/application/UnsyncedScrapUserReader.java
  src/main/java/org/terning/terningserver/external/scrap/application/UnsyncedScrapUserReaderImpl.java
  src/main/java/org/terning/terningserver/external/scrap/application/port/ScrapSyncMarker.java
  src/main/java/org/terning/terningserver/external/scrap/application/port/ScrapSyncNotifier.java
  src/main/java/org/terning/terningserver/external/scrap/application/port/UnsyncedScrapMarker.java
  src/main/java/org/terning/terningserver/external/scrap/application/port/UnsyncedScrapUserReader.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/ReadUnsyncedScrapUsersService.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/ScrapSyncCoordinatorService.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/SyncUnsyncedUsersService.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/UnsyncedScrapMarkerService.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/UnsyncedScrapUserReaderService.java
  src/main/java/org/terning/terningserver/external/scrap/application/usecase/ReadUnsyncedScrapUsersUseCase.java
  src/main/java/org/terning/terningserver/external/scrap/application/usecase/ScrapSyncOrchestrator.java
  src/main/java/org/terning/terningserver/external/scrap/application/usecase/SyncUnsyncedUsersUseCase.java
  src/main/java/org/terning/terningserver/external/scrap/common/failure/ScrapExternalErrorCode.java
  src/main/java/org/terning/terningserver/external/scrap/common/failure/ScrapExternalException.java
  src/main/java/org/terning/terningserver/external/scrap/config/OpsApiClient.java
  src/main/java/org/terning/terningserver/external/scrap/dto/request/ScrapUserIdsRequest.java
  src/main/java/org/terning/terningserver/external/scrap/scheduler/ScrapSyncScheduler.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryImpl.java
Labels: ✨ feat, 🦊장순🦊, size/L

#216 [✨ feat] 회원가입 시 FCM 토큰 저장 로직 구현
  src/main/java/org/terning/terningserver/auth/application/signup/AuthSignUpServiceImpl.java
  src/main/java/org/terning/terningserver/auth/dto/request/SignUpRequestDto.java
  src/main/java/org/terning/terningserver/external/config/WebClientConfig.java
  src/main/java/org/terning/terningserver/external/dto/request/CreateUserRequest.java
  src/main/java/org/terning/terningserver/external/notification/NotificationUserClient.java
Labels: ✨ feat, size/M

#223 [🔀 merge] [4차] 코드 리펙토링 사항 적용 (2)
  build.gradle
  src/main/java/org/terning/terningserver/TerningserverApplication.java
  src/main/java/org/terning/terningserver/auth/application/signin/AuthSignInServiceImpl.java
  src/main/java/org/terning/terningserver/auth/application/signup/AuthSignUpServiceImpl.java
  src/main/java/org/terning/terningserver/auth/dto/request/SignUpRequestDto.java
  src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java
  src/main/java/org/terning/terningserver/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/controller/UserProfileController.java
  src/main/java/org/terning/terningserver/controller/swagger/UserSwagger.java
  src/main/java/org/terning/terningserver/domain/Scrap.java
  src/main/java/org/terning/terningserver/domain/User.java
  src/main/java/org/terning/terningserver/domain/enums/PushNotificationStatus.java
  src/main/java/org/terning/terningserver/domain/vo/SyncStatus.java
  src/main/java/org/terning/terningserver/dto/user/request/PushStatusUpdateRequest.java
  src/main/java/org/terning/terningserver/dto/user/response/ProfileResponseDto.java
  src/main/java/org/terning/terningserver/exception/enums/ErrorMessage.java
  src/main/java/org/terning/terningserver/exception/enums/SuccessMessage.java
  src/main/java/org/terning/terningserver/external/config/WebClientConfig.java
  src/main/java/org/terning/terningserver/external/dto/FcmTokenReissueRequiredResponse.java
  src/main/java/org/terning/terningserver/external/dto/request/CreateUserRequest.java
  src/main/java/org/terning/terningserver/external/notification/FcmTokenValidationClient.java
  src/main/java/org/terning/terningserver/external/notification/NotificationUserClient.java
  src/main/java/org/terning/terningserver/external/scrap/ScrapSyncMarkerImpl.java
  src/main/java/org/terning/terningserver/external/scrap/api/ScrapExternalApiController.java
  src/main/java/org/terning/terningserver/external/scrap/application/port/ScrapSyncMarker.java
  src/main/java/org/terning/terningserver/external/scrap/application/port/ScrapSyncNotifier.java
  src/main/java/org/terning/terningserver/external/scrap/application/port/UnsyncedScrapMarker.java
  src/main/java/org/terning/terningserver/external/scrap/application/port/UnsyncedScrapUserReader.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/ReadUnsyncedScrapUsersService.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/ScrapSyncCoordinatorService.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/SyncUnsyncedUsersService.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/UnsyncedScrapMarkerService.java
  src/main/java/org/terning/terningserver/external/scrap/application/service/UnsyncedScrapUserReaderService.java
  src/main/java/org/terning/terningserver/external/scrap/application/usecase/ReadUnsyncedScrapUsersUseCase.java
  src/main/java/org/terning/terningserver/external/scrap/application/usecase/ScrapSyncOrchestrator.java
  src/main/java/org/terning/terningserver/external/scrap/application/usecase/SyncUnsyncedUsersUseCase.java
  src/main/java/org/terning/terningserver/external/scrap/common/failure/ScrapExternalErrorCode.java
  src/main/java/org/terning/terningserver/external/scrap/common/failure/ScrapExternalException.java
  src/main/java/org/terning/terningserver/external/scrap/config/OpsApiClient.java
  src/main/java/org/terning/terningserver/external/scrap/dto/request/ScrapUserIdsRequest.java
  src/main/java/org/terning/terningserver/external/scrap/dto/response/UnsyncedScrapUserResponse.java
  src/main/java/org/terning/terningserver/external/scrap/dto/response/UnsyncedScrapUsersResponse.java
  src/main/java/org/terning/terningserver/external/scrap/scheduler/ScrapSyncScheduler.java
  src/main/java/org/terning/terningserver/external/user/application/UserSyncEventService.java
  src/main/java/org/terning/terningserver/external/user/application/UserSyncEvnetServiceImpl.java
  src/main/java/org/terning/terningserver/external/user/config/NotificationSyncTasklet.java
  src/main/java/org/terning/terningserver/external/user/config/UserSyncJobConfig.java
  src/main/java/org/terning/terningserver/external/user/domain/UserSyncEvent.java
  src/main/java/org/terning/terningserver/external/user/domain/UserSyncEventType.java
  src/main/java/org/terning/terningserver/external/user/respository/UserSyncEventRepository.java
  src/main/java/org/terning/terningserver/external/user/scheduler/UserSyncScheduler.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepository.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryCustom.java
  src/main/java/org/terning/terningserver/repository/scrap/ScrapRepositoryImpl.java
  src/main/java/org/terning/terningserver/service/UserService.java
  src/main/java/org/terning/terningserver/service/UserServiceImpl.java
Labels: 🔀 merge, 🐶정교🐶, size/XXL

#225 [🔨 fix] 스크랩 취소시, 스크랩 수에 대한 동시성 이슈를 해결하기 위해 비관적 락 적용
  .gitignore
  build.gradle
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepository.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
  src/test/java/org/terning/terningserver/service/ScrapServiceTest.java
Labels: 🔨 fix, size/L

#229 [🔨 fix] 서버 QA를 위한 테스트 및 수정 작업 진행
  .github/workflows/DOCKER-CD-STAGING.yml
  .github/workflows/DOCKER-CD.yml
  README.md
  src/main/java/org/terning/terningserver/auth/application/signin/AuthSignInServiceImpl.java
  src/main/java/org/terning/terningserver/auth/application/social/apple/AppleAuthTokenValidator.java
  src/main/java/org/terning/terningserver/auth/dto/request/SignInRequest.java
  src/main/java/org/terning/terningserver/auth/dto/response/SignInResponse.java
  src/main/java/org/terning/terningserver/config/SwaggerConfig.java
  src/main/java/org/terning/terningserver/config/WebMvcConfig.java
  src/main/java/org/terning/terningserver/domain/Scrap.java
  src/main/java/org/terning/terningserver/external/config/WebClientConfig.java
  src/main/java/org/terning/terningserver/external/notification/NotificationUserClient.java
  src/main/java/org/terning/terningserver/jwt/provider/JwtKeyProvider.java
  src/main/java/org/terning/terningserver/service/UserServiceImpl.java
Labels: 🔨 fix, 🐶정교🐶, size/M

#231 [🔀 merge] [4차] 코드 리펙토링 사항 적용 (3)
  .gitignore
  build.gradle
  src/main/java/org/terning/terningserver/auth/application/signin/AuthSignInServiceImpl.java
  src/main/java/org/terning/terningserver/auth/dto/request/SignInRequest.java
  src/main/java/org/terning/terningserver/external/notification/NotificationUserClient.java
  src/main/java/org/terning/terningserver/repository/internship_announcement/InternshipRepository.java
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
  src/main/java/org/terning/terningserver/service/UserServiceImpl.java
  src/test/java/org/terning/terningserver/service/ScrapServiceTest.java
Labels: 🔀 merge, 🐶정교🐶, size/L

#232 [🔨 fix] Docker 컨테이너 로그로도 로그 확인할 수 있도록 HTTP 요청/응답 로깅 설정 수정
  src/main/resources/logback-dev.xml
  src/main/resources/logback-prod.xml
Labels: 🔨 fix, size/M

#235 [🔀 merge] HTTP 요청/응답 수정사항 로깅 스테이징 서버 반영
  src/main/resources/logback-dev.xml
  src/main/resources/logback-prod.xml
Labels: 🔨 fix, size/M
