Repository teamterning/Terning-Server, pull requests merged in 2025-05, with the labels that each got.

#236 [🔨 fix] 스크랩 추가시, 스크랩 수에 대한 동시성 테스트 진행
  src/main/java/org/terning/terningserver/service/ScrapServiceImpl.java
  src/test/java/org/terning/terningserver/service/ScrapServiceTest.java
Labels: 🔨 fix, 🐰정윤🐰, size/L

#239 [feat] 소셜로그인 시, 알림서버와 운영서버의 유저를 동기화 하는 로직 추가
  src/main/java/org/terning/terningserver/auth/application/signin/AuthSignInServiceImpl.java
  src/main/java/org/terning/terningserver/external/notification/NotificationUserClient.java
Labels: ✨ feat, 🐶정교🐶, size/S

#244 [✨ feat] 일회성 유저 동기화 API 구현
  src/main/java/org/terning/terningserver/auth/api/AuthController.java
  src/main/java/org/terning/terningserver/auth/api/AuthSwagger.java
  src/main/java/org/terning/terningserver/auth/application/AuthService.java
  src/main/java/org/terning/terningserver/auth/application/syncUser/AuthSyncUserService.java
  src/main/java/org/terning/terningserver/auth/application/syncUser/AuthSyncUserServiceImpl.java
  src/main/java/org/terning/terningserver/auth/dto/request/FcmTokenSyncRequest.java
  src/main/java/org/terning/terningserver/common/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/common/exception/enums/SuccessMessage.java
Labels: ✨ feat, 🐶정교🐶, size/M

#245 [🔀 merge] [4차] 코드 리펙토링 사항 스테이징 서버에 적용 (7)
  README.md
  src/main/java/org/terning/terningserver/auth/api/AuthController.java
  src/main/java/org/terning/terningserver/auth/api/AuthSwagger.java
  src/main/java/org/terning/terningserver/auth/application/AuthService.java
  src/main/java/org/terning/terningserver/auth/application/syncUser/AuthSyncUserService.java
  src/main/java/org/terning/terningserver/auth/application/syncUser/AuthSyncUserServiceImpl.java
  src/main/java/org/terning/terningserver/auth/dto/request/FcmTokenSyncRequest.java
  src/main/java/org/terning/terningserver/common/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/common/exception/enums/SuccessMessage.java
Labels: 🔀 merge, 🐶정교🐶, size/L

#246 [🔀 merge] [4차] 코드 리펙토링 사항 메인 서버에 적용
  README.md
  src/main/java/org/terning/terningserver/auth/api/AuthController.java
  src/main/java/org/terning/terningserver/auth/api/AuthSwagger.java
  src/main/java/org/terning/terningserver/auth/application/AuthService.java
  src/main/java/org/terning/terningserver/auth/application/syncUser/AuthSyncUserService.java
  src/main/java/org/terning/terningserver/auth/application/syncUser/AuthSyncUserServiceImpl.java
  src/main/java/org/terning/terningserver/auth/dto/request/FcmTokenSyncRequest.java
  src/main/java/org/terning/terningserver/common/config/SecurityConfig.java
  src/main/java/org/terning/terningserver/common/exception/enums/SuccessMessage.java
Labels: 🐶정교🐶, 🎉deploy, size/L

#247 [🔀 merge] [4차] 코드 리펙토링 사항 메인 서버에 적용
  src/main/java/org/terning/terningserver/user/dto/response/ProfileResponseDto.java
Labels: 🐶정교🐶, 🎉deploy, size/XS
